#!/usr/bin/env bash
# Runs ON the VM (invoked by remote-deploy.sh). Renders the container env file
# from Google Secret Manager using the VM's attached service account — so no
# credentials live in the repo, in GitHub, or in a hand-maintained file.
#
#   render-env.sh SECRET_PREFIX PROJECT [OUT_FILE]
#
# Reads deploy/secrets.map (shipped alongside this script into /opt/vera) and,
# for each `basename = ENV[,ENV...]` line, fetches "<SECRET_PREFIX>-<basename>"
# and writes each ENV=value to OUT_FILE (0600). Compose injects OUT_FILE via
# env_file. Rendering every deploy keeps the file current with secret rotations.
set -euo pipefail

SECRET_PREFIX="$1"
PROJECT="$2"
OUT_FILE="${3:-/opt/vera/app.env}"
MAP_FILE="$(dirname "$0")/secrets.map"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
chmod 600 "$tmp"

{
  echo "# Generated by render-env.sh from Secret Manager — do not edit."
  # App-level, non-secret settings. VERA_ENV must be one of local/dev/staging/prod
  # (the Settings Literal has no `test`), so the GCP `test` env runs as `dev`.
  echo "VERA_ENV=dev"
  echo "VERA_LOG_LEVEL=INFO"
  # GCP project for the control-plane's Vertex AI (Gemini) post-call eval. Not a
  # secret (it's the same PROJECT the secrets are fetched from, already in plaintext
  # in the pipeline vars / AR image path). Setting it starts the post-call eval
  # consumer; unset leaves the feature dormant.
  echo "VERA_GCP_PROJECT=$PROJECT"
  # Auto-retry: on a low-fill form (completion_pct < tenant.retry_fill_threshold),
  # the control-plane re-queues the call instead of parking it in EXCEPTION_REVIEW,
  # bounded by tenant.max_retries. Control-plane-only; the worker ignores it.
  echo "VERA_FORM_AUTO_RETRY_ENABLED=true"
  # Outbound email sender identity for the Twilio Email API (credentials come from
  # secrets.map). veratechsolutions.ai is domain-authenticated in Twilio (em7583.*).
  echo "VERA_EMAIL_FROM=no-reply@veratechsolutions.ai"
} >> "$tmp"

while IFS= read -r line; do
  # Strip comments and surrounding whitespace; skip blanks.
  line="${line%%#*}"
  line="$(printf '%s' "$line" | tr -d '[:space:]')"
  [ -z "$line" ] && continue

  basename="${line%%=*}"
  envvars="${line#*=}"

  value="$(gcloud secrets versions access latest \
    --project="$PROJECT" --secret="${SECRET_PREFIX}-${basename}")"

  # Compose interpolates ${...}/$VAR in env_file values, so a literal `$` in a secret (e.g. a DB
  # password) would be eaten and the container would get a truncated value. Escape each `$` as `$$`;
  # Compose turns `$$` back into one `$`, so the container receives the secret verbatim.
  value="$(printf '%s' "$value" | sed 's/[$]/$$/g')"

  # Fan out one secret to one or more env vars (comma-separated).
  IFS=',' read -ra names <<< "$envvars"
  for name in "${names[@]}"; do
    printf '%s=%s\n' "$name" "$value" >> "$tmp"
  done
done < "$MAP_FILE"

mv "$tmp" "$OUT_FILE"
trap - EXIT
chmod 600 "$OUT_FILE"
