#!/usr/bin/env bash
# Runs ON the VM (invoked by remote-deploy.sh). Renders the container env file
# from Google Secret Manager using the VM's attached service account — so no
# credentials live in the repo, in GitHub, or in a hand-maintained file.
#
#   render-env.sh SECRET_PREFIX PROJECT [OUT_FILE]
#
# Reads deploy/secrets.map (shipped alongside this script into /opt/vera) and,
# for each `basename = ENV[,ENV...]` line, fetches "<SECRET_PREFIX>-<basename>"
# and writes each ENV=value to OUT_FILE (0600). Compose injects OUT_FILE via
# env_file. Rendering every deploy keeps the file current with secret rotations.
set -euo pipefail

SECRET_PREFIX="$1"
PROJECT="$2"
OUT_FILE="${3:-/opt/vera/app.env}"
MAP_FILE="$(dirname "$0")/secrets.map"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
chmod 600 "$tmp"

{
  echo "# Generated by render-env.sh from Secret Manager — do not edit."
  # App-level, non-secret settings. VERA_ENV must be one of local/dev/staging/prod
  # (the Settings Literal has no `test`), so the GCP `test` env runs as `dev`.
  echo "VERA_ENV=dev"
  echo "VERA_LOG_LEVEL=INFO"
} >> "$tmp"

while IFS= read -r line; do
  # Strip comments and surrounding whitespace; skip blanks.
  line="${line%%#*}"
  line="$(printf '%s' "$line" | tr -d '[:space:]')"
  [ -z "$line" ] && continue

  basename="${line%%=*}"
  envvars="${line#*=}"

  value="$(gcloud secrets versions access latest \
    --project="$PROJECT" --secret="${SECRET_PREFIX}-${basename}")"

  # Fan out one secret to one or more env vars (comma-separated).
  IFS=',' read -ra names <<< "$envvars"
  for name in "${names[@]}"; do
    printf '%s=%s\n' "$name" "$value" >> "$tmp"
  done
done < "$MAP_FILE"

mv "$tmp" "$OUT_FILE"
trap - EXIT
chmod 600 "$OUT_FILE"
