"""widen auth audit event check for tenant crud

Revision ID: 22683a464337
Revises: a047f496c95b
Create Date: 2026-07-30 17:38:20.535361

Adds the five tenant-lifecycle events a platform operator can now emit (VR2-30):
`tenant_created`, `tenant_updated`, `tenant_deactivated`, `tenant_reactivated`,
`tenant_user_invited`. Same pattern as a047f496c95b: drop-and-recreate the named CHECK
from the CURRENT enum — a no-op on a fresh DB and an in-place widen on an existing one.

The autogenerated body was discarded: it proposed dropping four unrelated partial /
expression indexes that alembic cannot compare against the models (repo CLAUDE.md).
"""

from collections.abc import Sequence

from alembic import op

from vera_core.models.enums import AuthEvent, values_of

revision: str = "22683a464337"
down_revision: str | None = "a047f496c95b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CONSTRAINT = "ck_auth_audit_log_event_type_valid"
_NEW_VALUES = (
    "tenant_created",
    "tenant_updated",
    "tenant_deactivated",
    "tenant_reactivated",
    "tenant_user_invited",
)


def _check(values: Sequence[str]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"CHECK (event_type IN ({quoted}))"


def _recreate(values: Sequence[str]) -> None:
    op.execute(f"ALTER TABLE auth_audit_log DROP CONSTRAINT IF EXISTS {_CONSTRAINT}")
    op.execute(f"ALTER TABLE auth_audit_log ADD CONSTRAINT {_CONSTRAINT} {_check(values)}")


def upgrade() -> None:
    _recreate(values_of(AuthEvent))


def downgrade() -> None:
    _recreate(tuple(v for v in values_of(AuthEvent) if v not in _NEW_VALUES))
