"""widen auth audit event check for tenant crud

Revision ID: 235ef15d5d1a
Revises: 952630394b76
Create Date: 2026-08-03 10:02:22.432003

Adds the five tenant-lifecycle events a platform operator can now emit (VR2-30):
`tenant_created`, `tenant_updated`, `tenant_deactivated`, `tenant_reactivated`,
`tenant_user_invited`. Same pattern as a047f496c95b: drop-and-recreate the named CHECK
from the CURRENT enum — a no-op on a fresh DB and an in-place widen on an existing one.

The autogenerated body was discarded: it proposed dropping four unrelated partial /
expression indexes that alembic cannot compare against the models (repo CLAUDE.md).

Regenerated on top of dev's head (952630394b76, VR2-104's password-reset merge chain)
when rebasing this branch onto dev, per team convention: a PR ships one linear chain,
never a merge-revision stub (the original a047f496c95b-based chain was
22683a464337 -> e529f5cac06d -> b4d7a95a60fb).
"""

from collections.abc import Sequence

from alembic import op

from vera_core.models.enums import AuthEvent, values_of

revision: str = "235ef15d5d1a"
down_revision: str | None = "952630394b76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CONSTRAINT = "ck_auth_audit_log_event_type_valid"
_NEW_VALUES = (
    "tenant_created",
    "tenant_updated",
    "tenant_deactivated",
    "tenant_reactivated",
    "tenant_user_invited",
)


def _check(values: Sequence[str]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"CHECK (event_type IN ({quoted}))"


def _recreate(values: Sequence[str]) -> None:
    op.execute(f"ALTER TABLE auth_audit_log DROP CONSTRAINT IF EXISTS {_CONSTRAINT}")
    op.execute(f"ALTER TABLE auth_audit_log ADD CONSTRAINT {_CONSTRAINT} {_check(values)}")


def upgrade() -> None:
    _recreate(values_of(AuthEvent))


def downgrade() -> None:
    _recreate(tuple(v for v in values_of(AuthEvent) if v not in _NEW_VALUES))
