"""add app_user.invited_by for onboarding traceability

Revision ID: 808fa9885ef1
Revises: 25e54e43fcf3
Create Date: 2026-07-06 19:34:33.797352

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "808fa9885ef1"
down_revision: str | None = "25e54e43fcf3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_user", sa.Column("invited_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_app_user_invited_by_app_user"),
        "app_user",
        "app_user",
        ["invited_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_app_user_invited_by_app_user"), "app_user", type_="foreignkey")
    op.drop_column("app_user", "invited_by")
    # ### end Alembic commands ###
