steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -f
      - vera-backend/docker/agent_worker.Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/vera-repo/agent-worker:latest
      - --cache-from
      - us-central1-docker.pkg.dev/$PROJECT_ID/vera-repo/agent-worker:latest
      - vera-backend

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/vera-repo/agent-worker:latest
    waitFor: [build]

options:
  logging: LEGACY
